# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='date_of_formation',
            field=models.DateField(),
        ),
    ]
